### ISSUE TITLE
1.11.6 버그인 것 같습니다.

### ISSUE THREAD

**Issue by ofsoul01** [xpressengine/xe-core#2417]
app : Apache/2.4.18 (Ubuntu)

xe_version : 1.11.6

php : 7.1.33-1+ubuntu16.04.1+deb.sury.org+1

db_type : mysqli

use_rewrite : Y

use_db_session : Y

 
서버정보는 이렇게 되구요.

1. 글을 등록하려고 등록을 누르면 움직이지가 않습니다.

그런데 글은 등록이 돼 있네요?

수정도 마찬가지 입니다.

 

2. 애드온 문제인가 싶어서 애드온 체크해제하면..  쿼리id 가 잘못됐습니다. 뜨고...

에잇.. 삭제하자 하고 삭제 누르면.. 페이지 로딩할 수 없다고 에러뜹니다.

 

3. 관리자 페이지에서 메뉴를 변경하려고 해도.. 저장된 내용이 없습니다. 라는 에러가 출력되면서 메뉴 변경이 되지 않습니다.

4. 관리자 페이지에서 글삭제가 되지 않습니다.

5. 현재 짧은 주소를 사용중이고.. 동작이 되고.. rewrite_mod도 동작중인데..

PHP Version(Ver. 7.1.33-1+ubuntu16.04.1+deb.sury.org+1) : 가능
퍼미션 : 가능
XML 라이브러리 : 가능
Session.auto_start 설정 : 가능
ICONV 라이브러리 : 가능
GD 라이브러리 : 가능
Extension: fileinfo : 가능
DB : 가능
 XE 1.11.6 사용이 가능합니다.

 짧은 주소를 사용할 수 없습니다. 웹 서버 담당자에게 rewrite_mod지원 여부를 확인 바랍니다.

 이렇게 나옵니다....

**Comment by bjrambo** [comment]
반응이 없는경우 php자체의 에러로그가 필요할 수 있습니다.

서버내의 error log 를 확인해보셔야 합니다.

웹호스팅일 경우 웹호스팅에 PHP 500서버에러에 대한 로그를 달라고 요청해보세요.

**Comment by ofsoul01** [comment]
[Tue Nov 12 03:35:33.586101 2019] [php7:error] [pid 30459] [client 66.249.73.154:44913] PHP Fatal error:  Uncaught Error: Call to a member function getNextPage() on null in /home/cuniculus/ofsoul.com/files/cache/template_compiled/caefc61b8237db6085981d0748d874a2.compiled.php:249\nStack trace:\n#0 /home/cuniculus/ofsoul.com/classes/template/TemplateHandler.class.php(430): include()\n#1 /home/cuniculus/ofsoul.com/classes/template/TemplateHandler.class.php(197): TemplateHandler->_fetch('file:///home/cu...')\n#2 /home/cuniculus/ofsoul.com/classes/display/HTMLDisplayHandler.php(61): TemplateHandler->compile('./modules/board...', 'list.html')\n#3 /home/cuniculus/ofsoul.com/classes/display/DisplayHandler.class.php(64): HTMLDisplayHandler->toDoc(Object(boardView))\n#4 /home/cuniculus/ofsoul.com/classes/module/ModuleHandler.class.php(1153): DisplayHandler->printContent(Object(boardView))\n#5 /home/cuniculus/ofsoul.com/index.php(59): ModuleHandler->displayContent(Object(boardView))\n#6 {main}\n  thrown in /home/cuniculus/ofsoul.com/files/cache/template_compiled/caefc61b8237db6085981d0748d874a2.compiled.php on line 249

[Tue Nov 12 13:25:01.026936 2019] [php7:emerg] [pid 3868] [client 218.156.197.13:14812] PHP Parse error:  syntax error, unexpected end of file in /home/cuniculus/ofsoul.com/files/cache/queries/document.getDocumentList.1.11.6.mysqli.cache.php on line 123, referer: http://ofsoul.com/

이렇게 나온다는데요;;;

**Comment by hackmod** [comment]
> 쿼리id 가 잘못됐습니다. 뜨고

xml 쿼리를 php 쿼리 캐시 생성시키는 과정에서 퍼미션이 오류가 있는 경우 위와 같이 쿼리 id가 잘못되었다고 뜨더군요. 업그레이드 과정에서 퍼미션 설정이 잘못된 것 같습니다

**Comment by kms0219kms** [comment]
본 XE1 버전의 개발은 작년 2월부터 사실상 중단 상태입니다.

이 문제가 계속된다면, XE1의 업데이트 버전인 [Rhymix](https://rhymix.org)으로 업데이트 해보시기 바랍니다.

업데이트 방법은 [여기](https://rhymix.org/manual/introduction/xe-upgrade)를 참고하시면 됩니다.

제대로 된 답변 드리지 못한 점 죄송합니다.
